import type { Metadata } from "next";
import { Sora, Plus_Jakarta_Sans } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { LAUNCHED, PROGRAM_NAME } from "./data";
import { Icon } from "./icons";

/**
 * "Kinetic Longevity" type system, scoped to /healthy only — loaded here
 * rather than the root layout so the rest of the site keeps its own
 * Space Grotesk / DM Sans fonts untouched. Exposed as font-kinetic-heading /
 * font-kinetic-body Tailwind utilities via the matching entries in
 * globals.css's @theme block.
 */
const sora = Sora({
  variable: "--font-kinetic-heading",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-kinetic-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const description =
  "Brian's Human Longevity Program for adults over 40: support your energy, strengthen your body, support your focus and find your calm, with supplement picks explained from the clinical research.";

/**
 * Next merges metadata one level deep, so a page that sets `openGraph` replaces
 * this whole object. Every page spreads it and adds its own title, description
 * and url, or shares lose the image and site name and point og:url at /healthy.
 */
export const healthyOpenGraph = {
  siteName: "GetBrian Healthy",
  type: "website",
  locale: "en_US",
  images: [{ url: "/healthy/brand/og-image.png", width: 1200, height: 630, alt: "GetBrian Healthy" }],
} satisfies NonNullable<Metadata["openGraph"]>;

export const metadata: Metadata = {
  title: {
    default: `${PROGRAM_NAME} | GetBrian Healthy`,
    template: `%s | ${PROGRAM_NAME}`,
  },
  description,
  alternates: { canonical: "/healthy" },
  // Draft figures must not be indexed. See LAUNCHED in data.ts.
  robots: LAUNCHED ? { index: true, follow: true } : { index: false, follow: false },
  openGraph: { ...healthyOpenGraph, title: PROGRAM_NAME, description, url: "/healthy" },
  // Replaces the root layout's icons (metadata merges one level deep). The root
  // app/favicon.ico is still emitted on every route, declared 48x48, so these
  // declare 16 and 32 as well: browsers take the exact size match, which gives
  // /healthy its own tab icon at 1x and 2x. Generated by `npm run brand:healthy`.
  icons: {
    icon: [
      { url: "/healthy/brand/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/healthy/brand/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/healthy/brand/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/healthy/brand/apple-touch-icon.png", sizes: "180x180" }],
  },
};

const nav = [
  { href: "/healthy#picks", label: "Brian's picks" },
  { href: "/healthy/method", label: "How Brian picks" },
  { href: "/healthy/about", label: "About" },
];

const linkClass =
  "inline-flex min-h-11 items-center rounded-lg px-3 text-base font-medium text-fg-muted transition-colors duration-200 hover:text-brand-navy focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kinetic-primary-electric";

export default function HealthyLayout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className={`${sora.variable} ${plusJakartaSans.variable} flex min-h-full flex-1 flex-col text-[1.0625rem] sm:text-lg`}
    >
      {/* FTC guidance and iHerb's terms both want the disclosure up front, above the fold.
          The legal sentence and its link are unchanged from before this reskin. */}
      <div className="bg-slate-900 px-4 py-1.5 text-xs font-medium tracking-wide text-slate-300">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-2">
          <div className="flex flex-wrap items-center gap-2">
            <span className="inline-block h-2 w-2 animate-pulse rounded-full bg-kinetic-teal-on-dark" aria-hidden="true" />
            <span>Brian may earn a commission when you buy through links on these pages.</span>
            <Link href="/healthy/disclosures" className="font-semibold text-white underline hover:text-kinetic-teal-on-dark">
              How that works
            </Link>
          </div>
        </div>
      </div>

      {/* Opaque, not frosted: the Healthy mark's counter is white, so over a
          see-through header it showed as a white patch whenever the dark goal
          tiles scrolled underneath. */}
      <header className="sticky top-0 z-40 border-b border-border bg-bg">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 sm:px-6">
          <Link
            href="/healthy"
            className="flex min-h-11 items-center gap-3 rounded-lg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kinetic-primary-electric"
          >
            {/* A pre-sized 3x PNG served as-is: next/image would re-encode the
                flat logo at quality 75 and soften its edges. */}
            <Image
              src="/healthy/brand/healthy-mark.png"
              alt=""
              aria-hidden="true"
              width={51}
              height={44}
              loading="eager"
              unoptimized
              className="h-11 w-auto"
            />
            <span className="font-heading text-lg leading-tight font-semibold text-brand-navy">
              GetBrian <span className="text-kinetic-primary-electric">Healthy</span>
            </span>
          </Link>

          <nav aria-label="Healthy" className="hidden md:block">
            <ul className="flex items-center gap-1">
              {nav.map((item) => (
                <li key={item.href}>
                  <Link href={item.href} className={linkClass}>
                    {item.label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          {/* No orange header button: orange is reserved for retailer (Buy) buttons, and on a
              product page a second call to action here competed with Buy. */}

          {/* No-JS disclosure menu for small screens. */}
          <details className="group relative md:hidden">
            <summary className="flex min-h-11 cursor-pointer list-none items-center rounded-lg border border-border-strong px-4 font-medium text-brand-navy [&::-webkit-details-marker]:hidden">
              Menu
            </summary>
            <nav
              aria-label="Healthy"
              className="absolute right-0 z-50 mt-2 w-56 rounded-xl border border-border bg-bg p-2 shadow-lg"
            >
              <ul>
                {nav.map((item) => (
                  <li key={item.href}>
                    <Link href={item.href} className={`${linkClass} w-full`}>
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          </details>
        </div>
      </header>

      <main className="flex-1">{children}</main>

      <footer className="border-t border-border bg-slate-950 text-slate-300">
        <div className="mx-auto max-w-6xl px-4 py-10 text-base sm:px-6">
          <div className="mb-8 flex items-start gap-3 rounded-xl border border-slate-800 bg-slate-900/90 p-5">
            <Icon name="shield" size={22} className="mt-0.5 text-amber-400" />
            <div className="space-y-1">
              <p className="font-kinetic-heading text-xs font-extrabold uppercase tracking-wider text-white">
                The small print
              </p>
              <p className="text-sm leading-relaxed text-slate-400">
                General information only, not medical advice. Supplements are not a substitute for a
                varied diet or for care from your doctor. Statements about supplements have not been
                evaluated by the Food and Drug Administration.
              </p>
            </div>
          </div>
          <div className="flex flex-col justify-between gap-6 border-b border-slate-800 pb-8 md:flex-row md:items-center">
            <div className="flex items-center gap-4">
              {/* The mark only works on white, so on the dark footer it sits on a tile. */}
              <span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-white">
                <Image src="/healthy/brand/healthy-mark.png" alt="" aria-hidden="true" width={40} height={34} unoptimized className="h-[34px] w-auto" />
              </span>
              <div className="space-y-1">
                <span className="font-kinetic-heading text-xl font-extrabold text-white">GetBrian Healthy</span>
                <p className="text-sm text-slate-400">An independent, evidence-first review of longevity supplements.</p>
              </div>
            </div>
            <ul className="flex flex-wrap items-center gap-x-2 gap-y-1">
              <li>
                <Link href="/healthy/disclosures" className={`${linkClass} text-slate-300! hover:text-white!`}>
                  Disclosures
                </Link>
              </li>
              <li>
                <Link href="/healthy/about" className={`${linkClass} text-slate-300! hover:text-white!`}>
                  About and contact
                </Link>
              </li>
              <li>
                <Link href="/" className={`${linkClass} text-slate-300! hover:text-white!`}>
                  GetBrian home
                </Link>
              </li>
            </ul>
          </div>
          <div className="flex flex-col items-center justify-between gap-4 pt-6 text-sm text-slate-500 sm:flex-row">
            <p>
              &copy; {new Date().getFullYear()} GetBrian. An independent project, not affiliated with
              Human Longevity, Inc.
            </p>
            <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider text-slate-500">
              <span>Re-checked every 6 months</span>
              <span className="text-slate-700">&middot;</span>
              <span className="text-emerald-400">No paid placements</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
